name: CI-Pipeline

on : push

jobs:
  project-testing:
    runs-on : ubuntu-latest

    steps:
      - name : checkout code
        uses: actions/checkout@v3

      - name : setup python
        uses : actions/setup-python@v2
        with:
          python-version: '3.10'

      - name : install dependcies
        run: |
          pip install -r requirements.txt
      - name : run pipeline
        env :
          DAGSHUB_PAT : ${{secrets.DAGSHUB_PAT}}
        run : |
          dvc repro

      - name : run model test
        env :
            DAGSHUB_PAT : ${{secrets.DAGSHUB_PAT}}
        run: |
          python -m unittest tests/test_model.py

      - name : promote model to production
        if : success()
        env :
              DAGSHUB_PAT : ${{secrets.DAGSHUB_PAT}}
        run : |
          python scripts/promote_model.py

      - name : test flask app
        if : success()
        env :
              DAGSHUB_PAT : ${{secrets.DAGSHUB_PAT}}
        run : |
          python -m unittest tests/test_flask_app.py

      - name : Docker log in
        if : success()
        uses : docker/login-action@v2
        with:
          username : ${{secrets.DOCKERHUB_USERNAME}}
          password : ${{secrets.DOCKERHUB_ACESSTOKEN}}

      - name : docker image
        if : success()
        run : docker build - t ${{secrets.DOCKERHUB_USERNAME}}/mini-project:latest .

      - name : docker image push
        if : success()
        run : docker push ${{secrets.DOCKERHUB_USERNAME}}/mini-project:latest
